version: 0.0
os: linux
files:
  - source: /run.sh
    destination: /app/ebs
  - source: /src
    destination: /app/ebs
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
   
 
